#!/bin/bash

echo "🚀 Deploy Manual - Execute no servidor:"
echo ""
echo "1. Conecte ao servidor:"
echo "   ssh root@72.60.157.115"
echo ""
echo "2. Execute os comandos:"
echo "   cd /opt/whatsapp-network"
echo "   git pull origin main"
echo "   npm install"
echo "   pm2 restart whatsapp-network"
echo ""
echo "3. Verifique se está funcionando:"
echo "   pm2 status"
echo ""
echo "4. Acesse o site:"
echo "   https://disparozap.site"
echo ""
echo "🎯 Após o deploy, você verá:"
echo "   ✅ Botão 'Limpar Sessão' amarelo"
echo "   ✅ Debug visual na interface"
echo "   ✅ Melhor verificação de conexão"
